### ISSUE TITLE
Logo modification?

### ISSUE THREAD

**Issue by VoronaAV23** [In-tech-gration-Cohort-0x02/Bookaholics#9]
Change name to  Bookaholics  
Create logos of  different sizes 
favicon 
16x16 pixels

**Comment by leonalkalai** [comment]
Responsive logo is finished. The type is svg and set as a background. 
Favicon is finished. Incuded sizes (  196x196, 120x120, 96x96, 32x32, 16x16).
@VoronaAV23 @Amlima1 @saligaros @MaryRichelle @ozgurozbekuk

**Comment by MaryRichelle** [comment]
Yes @leonalkalai  we can do the but make sure to add h1 top level heading It signifies the most important heading on the page and should reflect the main topic or purpose of the content. or perhaps you can create a branch and purpose your changes.

**Comment by MaryRichelle** [comment]
if its done and approved by team maybe you can work on it and add it in html head tag [check here](https://github.com/orgs/In-tech-gration-Cohort-0x02/projects/2?pane=issue&itemId=48005250)

**Comment by leonalkalai** [comment]
1) `h1` i propose to be the first line of `main`.
If we put it inside header please suggest a position that it will have a real purpose  instead of just HTML.
2) Should i move the favicon html to a separate branch then? Because it is in same branch with logo HTML and i think its not good.
